FROM golang:1.19-alpine AS builder

# Install dependencies for building (if needed, e.g., git for fetching dependencies)
RUN apk add --no-cache gcc libc-dev make

WORKDIR /enclave_in_web3

COPY . .

RUN go mod tidy

RUN go build -o bin/enclave-client ./cmd/client/main.go

FROM alpine:latest

WORKDIR /enclave_in_web3

# Install necessary dependencies for running the app (e.g., libc)
#RUN apk add --no-cache libc6-compat

COPY --from=builder /enclave_in_web3/bin/enclave-client ./
COPY --from=builder /enclave_in_web3/conf/application_client.yml ./conf/application.yml

EXPOSE 10000

#CMD ["sleep", "infinity"]
CMD ["./enclave-client"]