FROM golang:1.19

WORKDIR /enclave_in_web3

COPY . .

RUN go mod tidy

RUN go build -o bin/enclave-keeper ./cmd/keeper/main.go

RUN mkdir ./bin/conf

RUN cp conf/application_keeper.yml ./bin/conf/application.yml

EXPOSE 1024

CMD ["./enclave-keeper"]