FROM golang:1.19

WORKDIR /enclave_in_web3

COPY . .

RUN go mod tidy

RUN go build -o bin/enclave-client ./cmd/client/main.go

RUN mkdir ./bin/conf

RUN cp conf/application_client.yml ./bin/conf/application.yml

EXPOSE 10000

CMD ["./enclave-client"]